

#Exercice 1 : Hello World

#print ( "hello world\n "* 4)

#Exercice 2

#print ((99**3)*8) 

#exercice 3

#false
#true
#false
#false
#True

#exercice 4

#computer_brand= "Hp"
#print (f"I have a {computer_brand} computer" )



#exercice5

#name= "lior"
#age= 20
#shoe_size= 45
#info= f" my name is {name}. I have {age}. My size shoes is {shoe_size}"
#print(info)



#exercice 6

#a=30
#b=20
#if a>b:
   # print("Hello World")



#exercice 7

number= int (input("give me a number:"))
if number % 2==0:
    print("it's even ")
else:
     print  ("it's odd") 



#exercice8

#name= input("what is your name?")
#if name == "lior":
    #print ( "you are the boss")
#else:
     #print( "sorry but I am the BOSS")


#exercice9


#height=int ( input("what is your height?"))
#if height > 145:
    #print ("you can drive")
#else:
    #print ("you must wait for drive")    